CREATE TABLE _Sede (
	Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR (60) NOT NULL,
	Direccion VARCHAR (60) NOT NULL,
	Telefono VARCHAR (8) NOT NULL
);

CREATE TABLE _Usuario (
	Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	Documento VARCHAR (8) UNIQUE NOT NULL,
	NombreA VARCHAR (16) NOT NULL,
	NombreB VARCHAR (16),
	ApellidoA VARCHAR (16) NOT NULL,
	ApellidoB VARCHAR (16),
	Usuario VARCHAR (16) NOT NULL UNIQUE,
	Clave VARCHAR (16) NOT NULL,
	Direccion VARCHAR (60),
	Telefono VARCHAR (8) NOT NULL,
	Foto Varchar(500)
);

CREATE TABLE _Producto (
	Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR (60) NOT NULL,
	Descripcion VARCHAR (144) NOT NULL,
	Tipo VARCHAR (20) NOT NULL,
	Marca VARCHAR (20) NOT NULL,
	Precio INT NOT NULL,
	Coste INT NOT NULL,
	Stock INT NOT NULL DEFAULT 0,
	Foto VARCHAR (500) NOT NULL
);

CREATE TABLE _Envio (
	Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	Destinatario VARCHAR (60) NOT NULL,
	Direccion VARCHAR (60) NOT NULL,
	FechaEntrega DATETIME NOT NULL
);

CREATE TABLE _Tipo (
	Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR (16) NOT NULL UNIQUE,
);

CREATE TABLE _UEsT (
	U_Id INT NOT NULL,
	T_Id INT NOT NULL,
	PRIMARY KEY (U_Id, T_Id),
	FOREIGN KEY (U_Id) REFERENCES _Usuario(Id),
	FOREIGN KEY (T_Id) REFERENCES _Tipo(Id)
);

CREATE TABLE _STieneU (
	S_Id INT NOT NULL,
	U_Id INT NOT NULL,
	PRIMARY KEY (S_Id, U_Id),
	FOREIGN KEY (S_Id) REFERENCES _Sede(Id),
	FOREIGN KEY (U_Id) REFERENCES _Usuario(Id)
);

CREATE TABLE _STieneP (
	S_Id INT NOT NULL,
	P_Id INT NOT NULL,
	PRIMARY KEY (S_Id, P_Id),
	FOREIGN KEY (S_Id) REFERENCES _Sede(Id),
	FOREIGN KEY (P_Id) REFERENCES _Producto(Id)
);

CREATE TABLE _UGestionaP (
	U_Id INT NOT NULL,
	P_Id INT NOT NULL,
	PRIMARY KEY (U_Id, P_Id),
	FOREIGN KEY (U_Id) REFERENCES _Usuario(Id),
	FOREIGN KEY (P_Id) REFERENCES _Producto(Id)
);

CREATE TABLE _URealizaE (
	U_Id INT NOT NULL,
	E_Id INT NOT NULL,
	PRIMARY KEY (U_Id, E_Id),
	FOREIGN KEY (U_Id) REFERENCES _Usuario(Id),
	FOREIGN KEY (E_Id) REFERENCES _Envio(Id)
);

CREATE TABLE _ETieneP (
	E_Id INT NOT NULL,
	P_Id INT NOT NULL,
	PRIMARY KEY (E_Id, P_Id),
	FOREIGN KEY (E_Id) REFERENCES _Envio(Id),
	FOREIGN KEY (P_Id) REFERENCES _Producto(Id)
);

INSERT INTO _Tipo (Nombre) VALUES
('Sin Registrar'),
('Cliente'),
('Delivery'),
('Administrativo'),
('Encargado'),
('Maestro') ;
